apiVersion: v1
kind: Service
metadata:
  name: ms-liveclass
spec:
  type: NodePort
  selector:
    app: ms-liveclass
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 8099
      nodePort: 30099
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-liveclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-liveclass
  template:
    metadata:
      labels:
        app: ms-liveclass
    spec:
      containers:
        - name: ms-liveclass
          image: hazem114/mslivecourse:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:h2:mem:liveclassdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
            - name: SPRING_DATASOURCE_USERNAME
              value: "sa"
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "org.h2.Driver"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.H2Dialect"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
          ports:
            - containerPort: 8099
