spring.application.name=MS-Evaluation

spring.datasource.url=jdbc:mysql://localhost:3306/formini_evaluation_db?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull
server.port=8081
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#  rabbit mq

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.mvc.converters.preferred-json-mapper=jackson
# Expose the prometheus endpoint
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
# Optional: Add common tags to your metrics
management.observations.key-values.application=${spring.application.name}
management.prometheus.metrics.export.enabled=true



