spring.application.name=MS-RECLAMATION
spring.datasource.url=jdbc:mysql://mysql-db:3306/formini_reclamation_db
spring.datasource.username=root
spring.datasource.password=
server.port=8093
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Nom de l'application
app.name=formini
app.frontend.url=http://localhost:4200


anthropic.api.key=AIzaSyDhe3_XpFHUVrdLlDQf0CCv3jFt5zcv_pw
anthropic.api.key2=AIzaSyC-JFuf_eA5go1tfbESwiO2ICRcxEDix3k
# ?? Mail ??????????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=inesjlasi588@gmail.com
spring.mail.password=awof cxoj auid oxcf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ?? Admin email destinataire ??????????????????????????
app.admin.email=inesjlassi245@gmail.com

# Jira Configuration
jira.url=https://ines-esprit.atlassian.net
jira.email=ines.jlassi@esprit.tn
jira.api.token=ATATT3xFfGF0qabnlGfNXPV-3axL1jUhQO5ohMYeD-cRx-XIuWqAn_kQiE0zvAqD_xQqVQT1VSNhpWmVFLv-cnSR8DqL31V4gYAspTX8UKWklE1qDF9IYMi-RRq5KjGGxL1289HyUgmHnQD44oKhdnHeKeR-7MPR3qZLnrkQ21lfbIcHcOViVsE=FFDE40AF
jira.project.key=SCRUM
jira.issue.type=Task

app.banned.words=insulte,con,merde,putain,idiot,stupide,menace,spam,arnaque
