apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-service
  labels:
    app: forum-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forum-service
  template:
    metadata:
      labels:
        app: forum-service
    spec:
      containers:
      - name: forum-service
        image: forum-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-db:3306/formini?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: forum-service
spec:
  selector:
    app: forum-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
