apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: session-management
          image: kthiriyoussef/session-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/session_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: session-management
  labels:
    app: session-management
spec:
  type: NodePort
  selector:
    app: session-management
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
